<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>
<div class="row">
    <div class="col-xs-12 col-md-2"></div>
    
    <div class="col-xs-12 col-md-8">
        
<h1>
    Components
    <a href="<?php echo $this->url->get("components/new"); ?>" class="btn btn-success fancybox fancybox.iframe"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
</h1>

<?php $this->flashSession->output();?>

<table align="center" class="table table-striped table-bordered table-hover dataTable" id="components-list">
    <thead>
        <tr>
            <th width="20px"></th>
            <th>Type</th>
            <th>Manufacturer</th>
            <th>Model</th>
            <th width="20px"></th>
         </tr>
    </thead>

    <tbody>
    <?php foreach ($page as $component) { ?>
        <tr id="<?php echo $component->id ?>">
            <td><a href="<?php echo $this->url->get("compatibility/setup?components_id=" . $component->id); ?>" class="btn btn-primary fancybox fancybox.iframe"><span class="glyphicon glyphicon-check" aria-hidden="true"></span></td>
            <td><?php echo $component->type ?></td>
            <td><?php echo $component->manufacturer ?></td>
            <td><?php echo $component->model ?></td>
            <td><a href="<?php echo $this->url->get("components/delete/" . $component->id); ?>" class="btn btn-transparent red-color delete"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
        </tr>
    <?php } ?>
    </tbody>


</table>

    </div>
    <div class="col-xs-12 col-md-2"></div>
</div>
<script>

$(document).ready(function() {

    $('#components-list').dataTable({
            "iDisplayLength": 100,
            aoColumns: [{"sName": "type"}, {"sName": "manufacturer"}, {"sName": "model"}, null, null]

        }).makeEditable({
            
            sUpdateURL: "<?php echo $this->url->get("components/ajaxsave") ?>",

            "aoColumns": [
                            null,
                            {
                                onblur: 'submit',
                                indicator: 'Saving Type ...'
                            },
                            {
                                onblur: 'submit',
                                indicator: 'Saving Manufacturer ...'
                            },
                            {
                                onblur: 'submit',
                                indicator: 'Saving Model ...'
                            },
                            null
                        ]
    });

    $('.delete').click(function(e){
        e.preventDefault();
        var url = $(this).attr('href');
        var answer = confirm ("Are you sure you want to delete from the database?");
        if (answer)
        {
            // Do it!
            window.location = url;
        }
    });


});

</script>