<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h1>Components</h1>

<table width="100%">
    <tr>
        <td align="center">
            <?php echo $this->tag->linkTo(array("", "Home", 'class' => 'btn btn-success')); ?>
            <?php echo $this->tag->linkTo(array("components/new", "Create", 'class' => 'btn btn-success fancybox fancybox.iframe')); ?>
        </td>
    </tr>
</table>

<?php $this->flashSession->output();?>

<table align="center" class="table table-striped table-bordered hover dataTable" id="components-list">
    <thead>
        <tr>
            <th>Type</th>
            <th>Manufacturer</th>
            <th>Model</th>
            <th width="20px"></th>
            <th width="20px"></th>
         </tr>
    </thead>

    <tfoot>
        <tr>
            <th>Type</th>
            <th>Manufacturer</th>
            <th>Model</th>
            <th></th>
            <th></th>
         </tr>
    </tfoot>

    <tbody>
    <?php foreach ($page->items as $component) { ?>
        <tr id="<?php echo $component->id ?>">
            <td><?php echo $component->type ?></td>
            <td><?php echo $component->manufacturer ?></td>
            <td><?php echo $component->model ?></td>
            <td><?php echo $this->tag->linkTo(array("compatibility/setup?components_id=" . $component->id, "Compatibility", "class" => "btn btn-success fancybox fancybox.iframe")); ?></td>
            <td><?php echo $this->tag->linkTo(array("components/delete/" . $component->id, "Delete", "class" => "btn btn-danger delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>


</table>

<script>

$(document).ready(function() {

    $('#components-list').dataTable({
            "iDisplayLength": 100,
            aoColumns: [{"sName": "type"}, {"sName": "manufacturer"}, {"sName": "model"}, null, null]

        }).makeEditable({
            
            sUpdateURL: "/compatibility/components/ajaxsave",

            "aoColumns": [
                            {
                                onblur: 'submit',
                                indicator: 'Saving Type ...'
                            },
                            {
                                onblur: 'submit',
                                indicator: 'Saving Manufacturer ...'
                            },
                            {
                                onblur: 'submit',
                                indicator: 'Saving Model ...'
                            },
                            null,
                            null
                        ]
    });

    $('.delete').click(function(e){
        e.preventDefault();
        var url = $(this).attr('href');
        var answer = confirm ("Are you sure you want to delete from the database?");
        if (answer)
        {
            // Do it!
            window.location = url;
        }
    });


});

</script>