<?php echo $this->getContent(); ?>

<?php $this->flashSession->output();?>

<h2><?php echo $motherboard->manufacturer;?> <?php echo $motherboard->model;?> </h2>

<table align="center" class="table table-striped table-bordered hover" id="motherboard-components-list">
	<thead>
		<tr>
			<th width="40%">Components</th>
			<!--th width="40%">Note</th-->
			<th width="1%"></th>
		</tr>
	</thead>

	<?php foreach($compatibility as $key => $val):?>
		<tr>
			<td><?php echo $val['component_detail']['type']?> <strong><?php echo $val['component_detail']['manufacturer']?> <?php echo $val['component_detail']['model']?></strong></td>
			<!--td><?php echo $val['note'];?></td-->
			<td><a href="<?php echo $this->url->get("motherboard/componentsAddDelete/" . $val['id']); ?>" class="btn btn-danger delete"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
		</tr>
	<?php endforeach;?>

<form action="<?php echo $this->url->get("motherboard/componentsAddSave"); ?>" method="POST">
	<input type="hidden" name="motherboard_id" value="<?php echo $motherboard->id;?>">

	<tr>
		<td>
			<select name="components_id" class="form-control">
				<?php foreach($components as $key => $val):?>
				<?php if( empty($compatibility[$val['id']]) && $val['type'] !="Motherboard" )://if this component is already add, dont need to show?>
			  	<option value="<?php echo $val['id'];?>"><?php echo $val['type'] . " " . $val['manufacturer'] . " " . $val['model'] ?></option>
			  <?php endif;?>
			  	<?php endforeach;?>
			</select>
		</td>
		<!--td><input type="text" class="form-control" placeholder="Note" name="note" value=""></td-->
		<td>
			<button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-plus" aria-hidden="true"></button>
		</td>
	</tr>

</form>

</table>