<?php echo $this->tag->form("motherboard/create") ?>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create motherboard</h1>
</div>

<table class="table table-striped table-bordered">
    <tr>
        <td align="right">
            <label for="manufacturer">Manufacturer</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("manufacturer", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td align="right">
            <label for="model">Model</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("model", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton(array("Save", "class"=>"btn btn-primary")) ?></td>
    </tr>
</table>

</form>
