<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<div class="row">
    <div class="col-xs-12 col-md-2"></div>
    
    <div class="col-xs-12 col-md-8">

    <h1>
        Motherboard
        <a href="<?php echo $this->url->get("motherboard/new"); ?>" class="btn btn-success fancybox fancybox.iframe"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
    </h1>

<?php $this->flashSession->output();?>


    <table align="center" class="table table-striped table-bordered table-hover dataTable" id="motherboard-list">
        <thead>
            <tr>
                <th width="10px"></th>
                <th>Manufacturer</th>
                <th>Model</th>
                <th width="10px"></th>
                <th width="10px"></th>
                <th width="10px"></th>
             </tr>
        </thead>

        <tbody>
        <?php foreach ($page as $motherboard) { ?>
            <tr id="<?php echo $motherboard->id;?>" class="ui-state-default">
                <td><a href="<?php echo $this->url->get("motherboard/motherboard/" . $motherboard->id); ?>" class="btn btn-transparent blue-color"><span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span></a></td>
                <td><?php echo $motherboard->manufacturer ?></td>
                <td><?php echo $motherboard->model ?></td>
                <td><a href="<?php echo $this->url->get("motherboard/componentsAdd/" . $motherboard->id); ?>" class="btn btn-transparent blue-color fancybox fancybox.iframe"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></a></td>
                <td><a href="<?php echo $this->url->get("motherboard/delete/" . $motherboard->id); ?>" class="btn btn-transparent red-color delete"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
                <td class="vert-align center move"><span class="glyphicon glyphicon-move gray-color" aria-hidden="true"></span></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>

    </div>
    <div class="col-xs-12 col-md-2"></div>
</div>
<script>

$(document).ready(function() {

    //Rows Reordering
    //function keeping the width of TR 
    $("#motherboard-list tbody").rowsReOrdering({
        sOrderURL: "<?php echo $this->url->get("motherboard/ajaxorder") ?>"
    });

    //editable datatables
    var table = $('#motherboard-list').dataTable({
            "bSort" : false,
            "iDisplayLength": 100,
            aoColumns: [ null, {"sName": "manufacturer"}, {"sName": "model"}, null, null, null]

        }).makeEditable({

            sUpdateURL: "<?php echo $this->url->get("motherboard/ajaxsave") ?>",
            "aoColumns": [
                            null,
                            {
                                onblur: 'submit',
                                indicator: 'Saving Manufacturer ...'
                            },
                            {
                                onblur: 'submit',
                                indicator: 'Saving Model ...'
                            },
                            null,
                            null,
                            null
                        ]

        });

    $('.delete').click(function(e){
        e.preventDefault();
        var url = $(this).attr('href');
        var answer = confirm ("Are you sure you want to delete from the database?");
        if (answer)
        {
            // Do it!
            window.location = url;
        }
    });


});

</script>