<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Compatibility</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav">
        
	    <li class="<?php echo ($this->router->getControllerName() == "index" || $this->router->getControllerName() == "") ? "active" : "";?>"><a href="<?php echo $this->url->get("") ?>">Home</a></li>

	    <li class="<?php echo ($this->router->getControllerName() == "motherboard") ? "active" : "";?>" ><a href="<?php echo $this->url->get("motherboard/search");?>">Motherboards</a></li>
		
		<li class="<?php echo ($this->router->getControllerName() == "components") ? "active" : "";?>"><a href="<?php echo $this->url->get("components/search");?>">Components</a></li>

		<li class="<?php echo ($this->router->getControllerName() == "os") ? "active" : "";?>"><a href="<?php echo $this->url->get("os/search");?>">Operating Systems</a></li>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>