
<?php echo $this->tag->form("os/create") ?>

<?php echo $this->getContent(); ?>

<?php $this->flashSession->output();?>

<div align="center">
    <h1>Create os</h1>
</div>

<table class="table table-striped table-bordered">
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="revision">Revision</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("revision", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="release_year">Release Of Year</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("release_year", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton(array("Save", "class"=>"btn btn-primary")) ?></td>
    </tr>
</table>

</form>
