<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h1>Operating System</h1>

<table width="100%">
    <tr>
        <td align="center">
            <?php echo $this->tag->linkTo(array("", "Home", 'class' => 'btn btn-success')); ?>
            <?php echo $this->tag->linkTo(array("os/new", "Create", 'class' => 'btn btn-success fancybox fancybox.iframe')); ?>
        </td>
    </tr>
</table>

<table align="center" class="table table-striped table-bordered hover dataTable" id="os-list">
    <thead>
        <tr>
            <th>Name</th>
            <th>Revision</th>
            <th>Release Year</th>
            <th width="20px"></th>
         </tr>
    </thead>

    <tfoot>
        <tr>
            <th>Name</th>
            <th>Revision</th>
            <th>Release Year</th>
            <th></th>
         </tr>
    </tfoot>

    <tbody>
    <?php foreach ($page as $o) { ?>
        <tr id="<?php echo $o->id ?>">
            <td><?php echo $o->name ?></td>
            <td><?php echo $o->revision ?></td>
            <td><?php echo $o->release_year ?></td>
            <td><?php echo $this->tag->linkTo(array("os/delete/" . $o->id, "Delete", "class" => "btn btn-danger delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>

</table>

<script>

$(document).ready(function() {

    $('#os-list').dataTable({
            "iDisplayLength": 100,
            aoColumns: [{"sName": "name"}, {"sName": "revision"}, {"sName": "release_year"}, null]

        }).makeEditable({
            AddURL: "/compatibility/os/create",
            sUpdateURL: "/compatibility/os/ajaxsave",
            "aoColumns": [
                            {
                                onblur: 'submit',
                                indicator: 'Saving Name ...'
                            },
                            {
                                onblur: 'submit',
                                indicator: 'Saving Revision ...'
                            },
                            {
                                onblur: 'submit',
                                indicator: 'Saving Release of Year ...'
                            },
                            null
                        ]

    });

    $('.delete').click(function(e){
        e.preventDefault();
        var url = $(this).attr('href');
        var answer = confirm ("Are you sure you want to delete from the database?");
        if (answer)
        {
            // Do it!
            window.location = url;
        }
    });

} );

</script>