<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>
<div class="row">
    <div class="col-xs-12 col-md-2"></div>
    
    <div class="col-xs-12 col-md-8">
        
<h1>
    Operating System
    <a href="<?php echo $this->url->get("os/new"); ?>" class="btn btn-success fancybox fancybox.iframe"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
</h1>


<table align="center" class="table table-striped table-bordered table-hover dataTable" id="os-list">
    <thead>
        <tr>
            <th>Name</th>
            <th>Revision</th>
            <th>Release Year</th>
            <th width="20px"></th>
         </tr>
    </thead>

    <tbody>
    <?php foreach ($page as $o) { ?>
        <tr id="<?php echo $o->id ?>">
            <td><?php echo $o->name ?></td>
            <td><?php echo $o->revision ?></td>
            <td><?php echo $o->release_year ?></td>
            <td><a href="<?php echo $this->url->get("os/delete/" . $o->id); ?>" class="btn btn-transparent red-color delete"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></a></td>
        </tr>
    <?php } ?>
    </tbody>

</table>

    </div>
    <div class="col-xs-12 col-md-2"></div>
</div>
<script>

$(document).ready(function() {

    $('#os-list').dataTable({
            "iDisplayLength": 100,
            aoColumns: [{"sName": "name"}, {"sName": "revision"}, {"sName": "release_year"}, null]

        }).makeEditable({
            AddURL: "<?php echo $this->url->get("os/create") ?>",
            sUpdateURL: "/compatibility/os/ajaxsave",
            "aoColumns": [
                            {
                                onblur: 'submit',
                                indicator: 'Saving Name ...'
                            },
                            {
                                onblur: 'submit',
                                indicator: 'Saving Revision ...'
                            },
                            {
                                onblur: 'submit',
                                indicator: 'Saving Release of Year ...'
                            },
                            null
                        ]

    });

    $('.delete').click(function(e){
        e.preventDefault();
        var url = $(this).attr('href');
        var answer = confirm ("Are you sure you want to delete from the database?");
        if (answer)
        {
            // Do it!
            window.location = url;
        }
    });

} );

</script>